name: 3dgs

data_folder: ../data
resize_scale: 0.2
image_number: 100
num_steps: 10000
num_points: 30000  # 2 ** 14
l1_weight: 0.8
l2_weight: 0.8
dssim_weight: 0.2
depth_weight: 0.1
lr: 5e-4
eval_interval: 500
output_folder: outputs4_scale02_point30000_l2loss_sample_
device: cuda
render:
  tile_size: 16